;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        comment-or-uncomment-region
        cua-cut-region
        cua-delete-region
        cua-paste
        sgml-slash
        yas-next-field-or-maybe-expand
        ))

(setq mc/cmds-to-run-once
      '(
        compile-goto-error
        end-of-buffer
        goto-line
        ido-switch-buffer
        isearch-repeat-forward
        js2-mode-show-node
        live-cycle-clj-coll
        magit-status
        mouse-buffer-menu
        mouse-save-then-kill
        mouse-set-secondary
        ns-copy-including-secondary
        rgrep
        smex
        undo-tree-visualize
        yas-expand
        ))
