(deftheme sam
  "Created 2014-03-26.")

(custom-theme-set-faces
 'sam
 '(default ((t (:family "Monaco" :foundry "apple" :width normal :height 120 :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "#f6f3e8" :background "#242424" :stipple nil :inherit nil))))
 '(cursor ((t (:foreground "#DCDCCC" :background "#656565"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((t (:family "Sans Serif"))))
 '(escape-glyph ((t (:weight bold :foreground "#ddaa6f"))))
 '(minibuffer-prompt ((t (:foreground "#e5786d"))))
 '(highlight ((t (:underline nil :foreground "#ffffff" :background "#454545"))))
 '(region ((t (:foreground "#f6f3e8" :background "#007fff"))))
 '(shadow ((((class color grayscale) (min-colors 88) (background light)) (:foreground "grey50")) (((class color grayscale) (min-colors 88) (background dark)) (:foreground "grey70")) (((class color) (min-colors 8) (background light)) (:foreground "green")) (((class color) (min-colors 8) (background dark)) (:foreground "yellow"))))
 '(secondary-selection ((t (:foreground "#f6f3e8" :background "#333366"))))
 '(trailing-whitespace ((t (:background "#CC9393"))))
 '(font-lock-builtin-face ((t (:weight bold :foreground "#e5786d"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#5F7F5F" :inherit (font-lock-comment-face)))))
 '(font-lock-comment-face ((t (:foreground "#99968b"))))
 '(font-lock-constant-face ((t (:foreground "#e5786d"))))
 '(font-lock-doc-face ((t (:foreground "#9FC59F" :inherit (font-lock-string-face)))))
 '(font-lock-function-name-face ((t (:foreground "#cae682"))))
 '(font-lock-keyword-face ((t (:weight bold :foreground "#8ac6f2"))))
 '(font-lock-negation-char-face ((t (:weight bold :foreground "#F0DFAF"))))
 '(font-lock-preprocessor-face ((t (:foreground "#94BFF3" :inherit (font-lock-builtin-face)))))
 '(font-lock-regexp-grouping-backslash ((t (:weight bold :foreground "#7F9F7F" :inherit (bold)))))
 '(font-lock-regexp-grouping-construct ((t (:weight bold :foreground "#F0DFAF" :inherit (bold)))))
 '(font-lock-string-face ((t (:foreground "#95e454"))))
 '(font-lock-type-face ((t (:weight bold :foreground "#92a65e"))))
 '(font-lock-variable-name-face ((t (:foreground "#cae682"))))
 '(font-lock-warning-face ((t (:weight bold :foreground "#ccaa8f" :inherit (error)))))
 '(button ((t (:underline (:color foreground-color :style line) :foreground "#f6f3e8" :background "#333333" :inherit (link)))))
 '(link ((t (:weight bold :underline (:color foreground-color :style line) :foreground "#8ac6f2"))))
 '(link-visited ((t (:weight normal :underline (:color foreground-color :style line) :foreground "#e5786d" :inherit (link)))))
 '(fringe ((t (:foreground "#DCDCCC" :background "#303030"))))
 '(header-line ((t (:box (:line-width -1 :color nil :style released-button) :foreground "#e7f6da" :background "#303030" :inherit (mode-line)))))
 '(tooltip ((t (:foreground "black" :background "lightyellow" :inherit (variable-pitch)))))
 '(mode-line ((t (:box (:line-width -1 :color nil :style released-button) :foreground "#f6f3e8" :background "#444444"))))
 '(mode-line-buffer-id ((t (:weight bold :foreground "#F0DFAF"))))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-highlight ((((class color) (min-colors 88)) (:box (:line-width 2 :color "grey40" :style released-button))) (t (:inherit (highlight)))))
 '(mode-line-inactive ((t (:weight light :box (:line-width -1 :color nil :style released-button) :foreground "#857b6f" :background "#444444" :inherit (mode-line)))))
 '(isearch ((t (:weight bold :foreground "#857b6f" :background "#343434"))))
 '(isearch-fail ((t (:foreground "#DCDCCC" :background "#8C5353"))))
 '(lazy-highlight ((t (:weight bold :foreground "#a0a8b0" :background "#384048"))))
 '(match ((t (:weight bold :foreground "#DFAF8F" :background "#2B2B2B"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch))))))

(provide-theme 'sam)
